spring.application.name=botTelegram
server.port=8080
logging.level.botTelegram=INFO
logging.level.org.telegram=DEBUG
telegram.bot.username=manolito_conducir_bot
telegram.bot.token=8410239677:AAE8R4QFiTVAvMY7SyoKsf0RP_g1z0imefs



# H2 / JPA

# H2 en archivo (persistente)
spring.datasource.url=jdbc:h2:file:./data/drivingbotdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Opcional: habilitar consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


